login page redesigns
Lodestone-Team/lodestone pull request #117
Opened 2023-01-20 04:40 UTC by Arcslogger

+ smol tweak of large buttons

2023-01-26 04:30 UTC, Arcslogger commented on package-lock.json
> +}
extra line is from prettier

2023-01-26 17:43 UTC, Ynng requested changes
Would it be possible have the background centered?
As in, as I shrink the width of the page, the entire page goes black.

If we center the image in the center, maybe we can get some of the colors to show up too?

2023-01-26 18:10 UTC, Ynng commented
And some minor issue with redirect.

2023-01-26 20:00 UTC, Ynng approved these changes

2023-01-26 20:13 UTC, Ynng requested changes
Actually a few more things: 
- "mixed/insecure content" is not the only network issue that could happen. We should probably link to our wiki instead
- The network settings warning should probably be on the CoreConnect page too, since that's likely when the problems are going to manifest themselves.

2023-01-28 20:49 UTC, Ynng commented
`You may need to adjust your network and browser settings. Learn more here`

2023-01-28 21:02 UTC, Ynng approved these changes

2023-01-28 21:02 UTC, merged