left nav tweaks
Lodestone-Team/lodestone pull request #167
Opened 2023-02-20 04:41 UTC by Arcslogger

attempts to fix the floaty feeling the nav currently has:
- reduced x-padding
- thinner width to mitigate padding 
- thinner font weight

also cleaned up some broken tailwind classes and unused imports

---

### screenshots:
(note: all screenshots are taken on a 1440p 27" monitor running macos) 
| before                                                                                                          | After                                |
| --------------------------------------------------------------------------------------------------------------- | ------------------------------------ |
| ![image](https://user-images.githubusercontent.com/58961173/220010729-9b38b0b7-8977-4e49-b001-976e403e8254.png) | ![image](https://user-images.githubusercontent.com/58961173/220010861-eb9fd281-58ea-4bf4-aad3-2cf6f0fe41a6.png) |

2023-02-20 04:42 UTC, Arcslogger commented
note: if things still feel strange then we might want to take a look at changing satoshi to something else. The more I work with it the more I realize it has kinda shit legibility at small font sizes

2023-02-20 05:32 UTC, Ynng requested changes
lgtm! can we also make everything larger, or would that take too long

2023-02-20 05:32 UTC, Ynng approved these changes
sry meant to approve

2023-02-20 06:46 UTC, NicholasLin718 requested changes
Resizing issue:
![image](https://user-images.githubusercontent.com/83772958/220032322-3671071b-aff0-4fff-b194-aa986feb2c73.png)

This is caused by the Menu button inside `UserMenu `using `w-full` in order to give the text inside the button a width to truncate with. However, the core settings icon is not included within the Menu button's `w-full`, so it will get cut off when a longer username is used.

2023-02-21 03:28 UTC, NicholasLin718 approved these changes

2023-02-21 03:29 UTC, merged