#145 Implement Minecraft player list component
Lodestone-Team/lodestone pull request #176
Opened 2023-02-25 07:50 UTC by kevinzhangTT

# Description

https://github.com/Lodestone-Team/lodestone/issues/145

Implements a Minecraft player list component that displays the player's username and avatar picture, and updates in real time as players join or leave the server. The profile pictures are retrieved from https://mc-heads.net/#basic using the player's UUID. The NAME button above the list allows for sorting usernames in alphabetical or reverse alphabetical order.

![image](https://user-images.githubusercontent.com/43940223/221345173-0961c425-908e-4f4d-a6c1-e8d173ccf98d.png)

If there is no one online, the text changes to say "No players online".

![image](https://user-images.githubusercontent.com/43940223/221345124-43d71751-b7ea-46ed-9ab5-531bc0bbe853.png)

The main files that contribute to this PR are are [MinecraftPlayerList.tsx](https://github.com/Lodestone-Team/lodestone/compare/0.4.3...145-0.4.3-player-list#diff-22ccce3d6d44067789bc988096cf61077cbe6acd43fb466403207181d741242b) and [PlayerListCard.tsx](https://github.com/Lodestone-Team/lodestone/compare/0.4.3...145-0.4.3-player-list#diff-8866a9890a7b4622468f92c6cc21296f81121ee96dccd918d7308c5946c6e5f6). MinecraftPlayerList.tsx mainly handles player data like setting the avatar and tracking online players, while PlayerListCard.tsx contains the UI.

[InstanceInfo.ts](https://github.com/Lodestone-Team/lodestone/compare/0.4.3...145-0.4.3-player-list#diff-a1480f44ddfd73db4591896dfd5eacb897e8f2575999d4acc06c04974ab3c0e4) and [EventStream.ts](https://github.com/Lodestone-Team/lodestone/compare/0.4.3...145-0.4.3-player-list#diff-ce81eee6c4968be3bd41724436bc659c835735ce4c9fd4a20ac190885289f084) also had to be modified in some way to support `Player` objects and updating the list of them to reflect in the UI in real time.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Extremely thorough testing B)

![minecraft-player-list-test](https://user-images.githubusercontent.com/43940223/221345039-731dd06d-1be5-425e-af5f-f716e058300a.gif)

2023-02-25 07:53 UTC, joeywangzr reviewed
otherwise lgtm

2023-02-25 07:53 UTC, joeywangzr commented on src/components/Minecraft/MinecraftPlayerList.tsx
> +  // JUST FOR TESTING
remove these comments

2023-02-25 08:23 UTC, Ynng requested changes
overall really nice, just a few small things
mostly regarding the player list use state

2023-02-25 08:23 UTC, Ynng commented on src/components/Minecraft/MinecraftPlayerList.tsx
> +    { type: 'MinecraftPlayer', uuid: '', name: ''}
this should be an empty array

2023-02-25 08:23 UTC, Ynng commented on src/components/Minecraft/MinecraftPlayerList.tsx
> +      setPlayerList(instance.player_list);
why do we have this state in the middle?
if it's for sorting, I believe we can use a `useMemo` instead

2023-02-25 08:23 UTC, Ynng commented on src/components/Minecraft/MinecraftPlayerList.tsx
> +  const avatarDimension = 128;
do we really need 128?

2023-02-25 08:29 UTC, Ynng commented
also the icon looks a bit small... can you @Arcslogger take a look next week?

2023-03-01 06:18 UTC, Ynng approved these changes
code looks good! let's merge this pr.


@CheatCod when can we get the player_list api changed merged to the backend?
https://github.com/Lodestone-Team/lodestone_core/tree/player_list_in_instance_info

2023-03-01 06:34 UTC, merged

2023-03-02 02:07 UTC, CheatCod commented
backend will follow up once the configurable refactor is merged in