macro config parsing in core
Lodestone-Team/lodestone pull request #319
Opened 2023-07-26 01:43 UTC by C0W0

# Description

Currently, there is no easy way for macro developers to render custom configs to the front end. This PR contains Typescript parsing logic, which runs independently of the Deno runtime to extract custom config templates defined by the macro developer into SettingManifests. We might need some corresponding frontend logic to test it out.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

*Note: make sure your files are formatted with rust-analyzer*

2023-07-27 00:51 UTC, Ynng commented
I think this PR is directed at the wrong branch, `core_dev` and `core_main` are read only, we should merge to `dev` instead.

2023-07-27 02:01 UTC, CheatCod requested changes
More comments on how everything works will be great

2023-07-27 02:01 UTC, CheatCod commented on core/src/macro_executor.rs
> +            }
this can be replaced with an iterator

2023-07-30 22:12 UTC, C0W0 commented on core/src/macro_executor.rs
> +            }
Wait how...

2023-07-30 22:36 UTC, CheatCod requested changes
add test cases please

2023-07-30 22:37 UTC, CheatCod requested changes
looks like some files are changed not related to this PR? you should revert them if that's the case

2023-08-01 03:27 UTC, C0W0 commented
@CheatCod added comments and fixed those irrelevant files. Just needed to do a merge with dev to get up to date. Also added unit test

2023-08-02 23:05 UTC, CheatCod approved these changes

2023-08-03 00:53 UTC, merged