feat: added logging for duplicate uuids
Lodestone-Team/lodestone pull request #337
Opened 2023-08-16 21:09 UTC by jhuang38

# Description

Added check with map for when duplicate UUIDs are detected (e.g. if a user copy-pastes an instance config file)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

*Note: make sure your files are formatted with rust-analyzer*

2023-08-19 21:44 UTC, Ynng requested changes
can we reuse `ret` and not build a separate map?

2023-08-20 19:45 UTC, CheatCod requested changes

2023-08-20 19:45 UTC, CheatCod commented on core/src/lib.rs
> +        }
why do we need a separate UUID map? You can just query the `ret` map

2023-08-24 00:31 UTC, CheatCod approved these changes

2023-08-24 02:21 UTC, merged